# document and style R code using a reusable workflow
name: call-doc-and-style-r
# on specifies the build triggers. See more info at https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows
on:
  # workflow_dispatch requires pushing a button to run the workflow manually. uncomment the following line to add:
  workflow_dispatch:
  push:
    branches: [main]
jobs:
  call-workflow:
    uses: nmfs-ost/ghactions4r/.github/workflows/doc-and-style-r.yml@main
  
